# ----------- CONFIGURABLE START -----------
title:            "LinkWorld Algorithm Blog"
description:      "Just do it."
url:              https://gdoulingwo.github.io/LinkWorld-Algorithm-Blog # Site url, without a slash at the end.
signoff:          "LinkWorld" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         About me
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"